  - name: ensure iptables is down
    service: name=iptables state=stopped enabled=no

  - name: install Percona repository
    template: src=templates/Percona.repo dest=/etc/yum.repos.d/Percona.repo

  - name: set permission
    file: path=/etc/yum.repos.d/Percona.repo owner=root group=root

  - name: install signature file for Percona repository
    template: src=templates/RPM-GPG-KEY-percona dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-percona

  - name: set permission for signature file
    file: path=/etc/pki/rpm-gpg/RPM-GPG-KEY-percona owner=root group=root

  - name: Install MySQL server and other packages
    yum: name={{ item }} state=present
    with_items:
      - percona-toolkit
      - vim
      - telnet
      - git
